## Lab Assignment: Numerical Computing using NumPy
Student:     Jeff McKendry

### Objective: To introduce numerical computing in Python using NumPy and understand NumPy arrays and operations.

### Instructions:
In this lab assignment, you will be introduced to numerical computing in Python using NumPy. You will learn how to create and manipulate NumPy arrays, perform mathematical operations on them, and apply built-in functions to analyze and transform the data.

You will be provided with the following five problems to solve. Please read the problem statement carefully and implement the solution using NumPy.

1. Create a 1D NumPy array of size 10, filled with zeros.
2. Create a 2D NumPy array with shape (3, 4), filled with random values.
3. Create a 3D NumPy array with shape (2, 3, 4), filled with ones.
4. Add two NumPy arrays element-wise.
5. Multiply two NumPy arrays element-wise.

### Deliverable:
Modify this notebook to include the python code as well as any documentation related to your submission.  Submit the notebook as your response in Blackboard.

### Grading Criteria:

Your lab assignment will be graded based on the following criteria:

- Correctness of the implementation
- Proper use of basic control structures and functions
- Code efficiency
- Clarity and readability of the code
- Compliance with the instructions and deliverables.

### Student Submission
1. Create a 1D NumPy array of size 10, filled with zeros.

In [1]:
import numpy as np

array_of_zeroes = np.zeros(10)
print(array_of_zeroes)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Create a 2D NumPy array with shape (3, 4), filled with random values.

In [5]:
import numpy as np
random_array = np.random.standard_normal(size = (3,4) )
print(random_array)

[[ 0.86832252 -0.0453649   0.44744798 -0.3404093 ]
 [-1.44585022  1.71411666 -1.00624746 -0.58360701]
 [ 0.65551624 -0.55057285  0.07650822  0.51994175]]


3. Create a 3D NumPy array with shape (2, 3, 4), filled with ones.

In [10]:
import numpy as np
array_of_ones = np.ones((2,3,4))
print(array_of_ones)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


4. Add two NumPy arrays element-wise.

In [11]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[17,12,13],[14,15,16]])

add_two_arrays = arr1 + arr2

print(add_two_arrays)

[[18 14 16]
 [18 20 22]]


5. Multiply two NumPy arrays element-wise.

In [12]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[17,12,13],[14,15,16]])

mult_two_arrays = arr1 * arr2

print(mult_two_arrays)

[[17 24 39]
 [56 75 96]]
